version: '3.7'
services:
  keycloak:
    image: "jboss/keycloak:11.0.3"
    container_name: "keycloak-server"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123
    ports:
      - "8180:8080"